### PR TITLE
Remove Rails dependency.

### PR DESCRIPTION
**Pull request by abuiles**

### CODE REVIEW

**Comment by joefiorini** [comment]
Thanks @abuiles, you rock!

**Comment by abuiles** [comment]
@joefiorini :shipit:

**Comment by abuiles** [comment]
@joefiorini btw, when do you think you could do a release with this? so I can take out this from my /lib/engines.

Btw, do you know how can I develop against master? Is just not clear to me since, the gem is a directory inside the project.

**Comment by joefiorini** [comment]
Good question. Maybe that's a bit short-sighted on my part. I should probably put the gemspec in the root. I'll try to get this released tomorrow. Cool?

-- 
Joe Fiorini

On March 3, 2014 at 8:00:00 PM, Adolfo Builes (notifications@github.com) wrote:

@joefiorini btw, when do you think you could do a release with this? so I can take out this from my /lib/engines.

Btw, do you know how can I develop against master? Is just not clear to me since, the gem is a directory inside the project.

**Comment by abuiles** [comment]
@joefiorini sounds good :), btw is user registration under the scope of this project too?

**Pull request merged**
